version: "3"
services:
  user-service:
    image: user-service:1.0
    command: "-Duser.timezone=GMT+0 -jar /user-service-1.0-SNAPSHOT.jar"
    ports:
      - "8400:8400"
    networks:
      - microservice-net
    depends_on:
      - service-mesh
    environment:
      _JAVA_OPTIONS: "-Xms1000m -Xmx1500m"
      SERVER_PORT: "8400"
      SPRING_PROFILES_ACTIVE: "docker"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  product-service:
    image: product-service:1.0
    command: "-Duser.timezone=GMT+0 -jar /product-service-1.0-SNAPSHOT.jar"
    ports:
      - "8500:8500"
    networks:
      - microservice-net
    depends_on:
      - service-mesh
    environment:
      _JAVA_OPTIONS: "-Xms1000m -Xmx1500m"
      SERVER_PORT: "8500"
      SPRING_PROFILES_ACTIVE: "docker"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  order-service:
    image: order-service:1.0
    command: "-Duser.timezone=GMT+0 -jar /order-service-1.0-SNAPSHOT.jar"
    ports:
      - "8600:8600"
    networks:
      - microservice-net
    depends_on:
      - service-mesh
    environment:
      _JAVA_OPTIONS: "-Xms1000m -Xmx1500m"
      SERVER_PORT: "8600"
      SPRING_PROFILES_ACTIVE: "docker"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure


networks:
  microservice-net:
    external: true