spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://database:3306/user_service?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 10000