spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?serverTimezone=UTC
    username: root
    password: a2131999
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 10000