server:
  port: 8088
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: galler-service
          predicates:
            - Path=/api/v1/gallery/**
          uri: http://galler-service:8100/
        - id: image-service
          predicates:
            - Path=/api/v1/image/**
          uri: http://galler-service:8200/
